name: Matrix
on: pull_request

jobs:
  node_version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6, 8, 10]
        # add extra environment variable 'is_ubuntu_8' set to true to job when ubuntu-latest, node 8 is ran!! 
        include:
          - os: ubuntu-latest
            node-version: 8
            is_ubuntu_8: "true"
        # exclude node versions for certain os in the matrix
        exclude:
          - os: ubuntu-latest
            node-version: 6
          - os: macos-latest
            node-version: 8

      # Runs a max of 2 jobs in the matrix at once.
      # max-parallel: 2

      # fail-fast option will stop other runs if one of the 3 fails
      # fail-fast: true
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8 }}
    steps:
      - name: Log Node Version
        run: node -v
        # Use this action to change node version in job
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log Node Version
        # log this variable IS_UBUNTU_8 if variable added to job
        run: | 
          node -v
          echo $IS_UBUNTU_8